language: java
services:
  - docker
jobs:
  include:
    - stage: Test
      script: ./gradlew check -i
    - stage: Push docker images
      if: branch = release && type != pull_request
      script: ./gradlew pushDockerImage -i